### ISSUE TITLE
OSSカレンダーのPHP8.1対応

### ISSUE THREAD

**Issue by hideosugimoto** [thinkingreed-inc/oss-calendar#28]
## 概要
OSSカレンダーのPHP8.1対応、及びLaravel9対応

## 該当ページ
全画面

## 背景と目的
OSSカレンダーの対応PHPバージョンを更新する。

## 最終的なゴール
PHP8.1、Laravel9.x、Nodev16.xにてOSSカレンダーが動作できるようにする。

**Comment by kkouta** [comment]
上記のプルリクの内容と他の修正を全てまとめたものを最後にプルリクとして出させていただきます。
