### ISSUE TITLE
ローディングにおいてスクロールが表示される

### ISSUE THREAD

**Issue by ryugonomura** [thinkingreed-inc/oss-calendar#3]
## 不具合概要
ローディングにおいてスクロールが表示される

## 該当ページ
ページを切り替える画面においてすべて

## 発生環境
- 環境：Windows１０
- ブラウザ：chrome
- バージョン：最新

## 再現手順
1. ログイン
2. ログイン後の画面でローディングが表示されるときにスクロールが表示される

## 本来の挙動
スクロールを出さない

## 修正しないとどう困るか
見た目の問題

## 原因
ローディングのコンポーネントにスクロールが表示されるようになっている

## 修正案
ローディングのコンポーネントにスクロール表示させないように修正する

**Comment by Remicck** [comment]
すみません、IDを間違えてCommitしてしまいました。
